### ISSUE TITLE
skript plugin is not working

### ISSUE THREAD

**Issue by bururaku** [PetteriM1/Pokkit#12]
Skript did not work properly in the following environment

OS:windows 10 home
CPU:Intel Core i7-8550U
RAM:16GB

Nukkit version: git-f02d671 (api version:1.0.9)
Pokkit version: 0.9
Skript(spigot plugin) version:[bensku-2.4-beta9](https://github.com/SkriptLang/Skript/releases/download/2.4-beta9/Skript.jar)

this is the error log
`22:12:21 [ERROR] [Pokkit] Error occurred while enabling Skript v2.4-beta9 (Is it up to date?)
java.lang.IllegalArgumentException: Data "[]"is not valid block data. Pokkit expects a number as the block data, as block states do not exist yet in MCPE.
        at org.bukkit.craftbukkit.v1_99_R9.CraftServer.createBlockData(CraftServer.java:210) ~[Pokkit-0.9.jar:0.9]
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1418) ~[Pokkit-0.9.jar:0.9]
        at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:335) ~[?:?]
        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:278) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:705) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:605) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:123) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:504) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:490) ~[?:?]
        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:473) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_211]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_211]
        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:466) ~[?:?]
        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:432) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:404) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:402) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Pokkit-0.9.jar:0.9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [Pokkit-0.9.jar:0.9]
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.enablePlugin(PokkitPluginLoader.java:69) [Pokkit-0.9.jar:0.9]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:722) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:558) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]`
Please fix it if possible.

**Comment by bururaku** [comment]
I forgot to list the java version
`java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)`

and I tried it with an older version(2.4-beta3) but got a similar error
`22:24:16 [ERROR] [Pokkit] Error occurred while enabling Skript v2.4-beta3 (Is it up to date?)
java.lang.IllegalArgumentException: Data "[]"is not valid block data. Pokkit expects a number as the block data, as block states do not exist yet in MCPE.
        at org.bukkit.craftbukkit.v1_99_R9.CraftServer.createBlockData(CraftServer.java:210) ~[Pokkit-0.9.jar:0.9]
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1418) ~[Pokkit-0.9.jar:0.9]
        at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:335) ~[?:?]
        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:295) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:704) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:605) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:123) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:504) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:490) ~[?:?]
        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:473) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_211]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_211]
        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:466) ~[?:?]
        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:432) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:404) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:402) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Pokkit-0.9.jar:0.9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [Pokkit-0.9.jar:0.9]
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.enablePlugin(PokkitPluginLoader.java:69) [Pokkit-0.9.jar:0.9]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:722) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:558) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]`

**Comment by Mortal-Dev** [comment]
the problem is right there in the error: Pokkit expects a number as the block data, as block states do not exist yet in MCPE, this won't get fixed until the actual vanilla game gets updated to support block states or the nukkit server gets updated to support it
