### ISSUE TITLE
Enderchest and fly method support?

### ISSUE THREAD

**Issue by jassyel** [PetteriM1/Pokkit#15]
java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.9.2
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:69) ~[?:?]
        at nl.rutgerkok.pokkit.entity.PokkitHumanEntity.getEnderChest(PokkitHumanEntity.java:57) ~[?:?]
        at de.fruxz.portableenderchest.commands.CMD_EnderChest.onCommand(CMD_EnderChest.java:17) ~[?:?]
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:274) ~[?:?]
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:752) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2803) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_231]
        at cn.nukkit.network.Network.processPackets(Network.java:197) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:180) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2092) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:83) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1125) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:904) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:881) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:566) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]

**Comment by RednedEpic** [comment]
Ender chest is supported in the latest version of Pokkit. It also seems like flight is supported, but adjusting flight speed is not.

**Comment by jassyel** [comment]
> Ender chest is supported in the latest version of Pokkit. It also seems like flight is supported, but adjusting flight speed is not.

I just tried the latest version of pokkit, however it no longer shows an error message, but it still doesn't work, neither flight nor enderchest

**Comment by jassyel** [comment]
New logs: 


16:46:15 [FATAL] Excepcion incontrolada al ejecutar el comando "workbench" en workbench: java.lang.UnsupportedOperationException: Pokkit doesn't support custom inventories of type WORKBENCH
        at nl.rutgerkok.pokkit.inventory.custom.PokkitCustomInventory.create(PokkitCustomInventory.java:33)
        at org.bukkit.craftbukkit.v1_99_R9.CraftServer.createInventory(CraftServer.java:254)
        at org.bukkit.craftbukkit.v1_99_R9.CraftServer.createInventory(CraftServer.java:249)
        at org.bukkit.Bukkit.createInventory(Bukkit.java:975)
        at com.bluecreeper111.jessentials.commands.Workbench.onCommand(Workbench.java:27)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:274)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
        at cn.nukkit.Server.dispatchCommand(Server.java:752)
        at cn.nukkit.Player.handleDataPacket(Player.java:2803)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:197)
        at cn.nukkit.network.Network.processBatch(Network.java:180)
        at cn.nukkit.Player.handleDataPacket(Player.java:2092)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:83)
        at cn.nukkit.Server.tick(Server.java:1125)
        at cn.nukkit.Server.tickProcessor(Server.java:904)
        at cn.nukkit.Server.start(Server.java:881)
        at cn.nukkit.Server.<init>(Server.java:566)
        at cn.nukkit.Nukkit.main(Nukkit.java:112)
