### ISSUE TITLE
spam in the console about events

### ISSUE THREAD

**Issue by jassyel** [PetteriM1/Pokkit#17]
Hi, I have no problem with this plugin but the console does not stop spamming the following:

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[?:?]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[?:?]

at nl.rutgerkok.pokkit.plugin.BukkitEventManager.fireEvent(BukkitEventManager.java:64) ~[?:?]

at nl.rutgerkok.pokkit.plugin.BukkitEventManager.callEvent(BukkitEventManager.java:49) ~[?:?]

at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.callEvent(PokkitPluginManager.java:79) ~[?:?]

at nl.rutgerkok.pokkit.pluginservice.EventTranslator.callUncancellable(EventTranslator.java:41) ~[?:?]

at nl.rutgerkok.pokkit.pluginservice.PlayerConnectEvents.onPlayerQuit(PlayerConnectEvents.java:67) ~[?:?]

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.close(Player.java:3582) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.close(Player.java:3568) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.kick(Player.java:3387) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.kick(Player.java:3361) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.processLogin(Player.java:1873) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:2223) ~[nukkit-stable.jar:?]

at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]

at cn.nukkit.network.Network.processPackets(Network.java:197) ~[nukkit-stable.jar:?]

at cn.nukkit.network.Network.processBatch(Network.java:180) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:2092) ~[nukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) ~[nukkit-stable.jar:?]

at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) ~[nukkit-stable.jar:?]

Error grabbing logs: unexpected EOF

**Comment by PetteriM1** [comment]
Please send the full error message

**Comment by jassyel** [comment]
Full logs

[36m20:50:29[m [[m[1;31mERROR[m[m] [Pokkit] Could not pass event PlayerQuitEvent to MudgeChat v3.0.3

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[?:?]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[?:?]

at nl.rutgerkok.pokkit.plugin.BukkitEventManager.fireEvent(BukkitEventManager.java:64) ~[?:?]

at nl.rutgerkok.pokkit.plugin.BukkitEventManager.callEvent(BukkitEventManager.java:49) ~[?:?]

at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.callEvent(PokkitPluginManager.java:79) ~[?:?]

at nl.rutgerkok.pokkit.pluginservice.EventTranslator.callUncancellable(EventTranslator.java:41) ~[?:?]

at nl.rutgerkok.pokkit.pluginservice.PlayerConnectEvents.onPlayerQuit(PlayerConnectEvents.java:67) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.close(Player.java:3582) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.close(Player.java:3568) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.kick(Player.java:3387) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.kick(Player.java:3361) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.processLogin(Player.java:1873) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:2223) ~[nukkit-stable.jar:?]

at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_212]

at cn.nukkit.network.Network.processPackets(Network.java:197) [nukkit-stable.jar:?]

at cn.nukkit.network.Network.processBatch(Network.java:180) [nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:2092) [nukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit-stable.jar:?]

at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [nukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:83) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1125) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:904) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:881) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:566) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-stable.jar:?]

Caused by: java.lang.NullPointerException

at me.mvdgechat3.Files.SetupPlayerManager.addToFile(SetupPlayerManager.java:88) ~[?:?]

at me.mvdgechat3.Files.SetupPlayerManager.removeFromManager(SetupPlayerManager.java:123) ~[?:?]

at me.mvdgechat3.Files.SetupPlayerManager.onLeave(SetupPlayerManager.java:58) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[?:?]

... 32 more

**Comment by PetteriM1** [comment]
No, do debugpaste and send the link or send the log file itself
