### ISSUE TITLE
Bossbar Api

### ISSUE THREAD

**Issue by jassyel** [PetteriM1/Pokkit#18]
Error Bossbar 

[36m23:51:27[m [[m[5;1;31mFATAL[m[m] Unhandled exception executing command "bm send test" in bossbarmessage: java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.9.3

at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:69)

at org.bukkit.craftbukkit.v1_99_R9.CraftServer.createBossBar(CraftServer.java:221)

at org.bukkit.Bukkit.createBossBar(Bukkit.java:1254)

at me.itsnathang.bossbarmessage.util.BossBarHandler.sendGlobal(BossBarHandler.java:39)

at me.itsnathang.bossbarmessage.commands.Message.sendBossBarMessage(Message.java:87)

at me.itsnathang.bossbarmessage.commands.CommandHandler.onCommand(CommandHandler.java:38)

at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:274)

at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)

at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)

at cn.nukkit.Server.dispatchCommand(Server.java:752)

at cn.nukkit.Player.handleDataPacket(Player.java:2803)

at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)

at cn.nukkit.network.Network.processPackets(Network.java:197)

at cn.nukkit.network.Network.processBatch(Network.java:180)

at cn.nukkit.Player.handleDataPacket(Player.java:2092)

at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)

at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)

at cn.nukkit.network.Network.processInterfaces(Network.java:83)

at cn.nukkit.Server.tick(Server.java:1125)

at cn.nukkit.Server.tickProcessor(Server.java:904)

at cn.nukkit.Server.start(Server.java:881)

at cn.nukkit.Server.<init>(Server.java:566)

at cn.nukkit.Nukkit.main(Nukkit.java:112)

[36m23:51:27[m [[m[1;31mERROR[m[m] Throwing

java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.9.3

at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:69) ~[?:?]

at org.bukkit.craftbukkit.v1_99_R9.CraftServer.createBossBar(CraftServer.java:221) ~[?:?]

at org.bukkit.Bukkit.createBossBar(Bukkit.java:1254) ~[?:?]

at me.itsnathang.bossbarmessage.util.BossBarHandler.sendGlobal(BossBarHandler.java:39) ~[?:?]

at me.itsnathang.bossbarmessage.commands.Message.sendBossBarMessage(Message.java:87) ~[?:?]

at me.itsnathang.bossbarmessage.commands.CommandHandler.onCommand(CommandHandler.java:38) ~[?:?]

at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:274) ~[?:?]

at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33) ~[nukkit-stable.jar:?]

at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-stable.jar:?]

at cn.nukkit.Server.dispatchCommand(Server.java:752) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:2803) ~[nukkit-stable.jar:?]

at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]

at cn.nukkit.network.Network.processPackets(Network.java:197) ~[nukkit-stable.jar:?]

at cn.nukkit.network.Network.processBatch(Network.java:180) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:2092) ~[nukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) ~[nukkit-stable.jar:?]

at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) ~[nukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68) ~[nukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:83) ~[nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1125) ~[nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:904) ~[nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:881) ~[nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:566) ~[nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-stable.jar:?]

**Comment by PetteriM1** [comment]
`UnsupportedOperationException: This method is not supported yet by Pokkit 0.9.3`

**Comment by PetteriM1** [comment]
Fixed in 78c107c I guess
