### ISSUE TITLE
CoreProtect database busy

### ISSUE THREAD

**Issue by jelebruh** [PetteriM1/Pokkit#32]
when i start CP with Pokkit i see
Receiver class org.sqlite.Conn does not define or inherit an implementation of the resolved method 'abstract boolean isValid(int)' of interface java.sql.Connection.
	at net.coreprotect.consumer.Process.validateConnection(Process.java:42)
	at net.coreprotect.consumer.Process.processConsumer(Process.java:248)
	at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by PetteriM1** [comment]
This doesn't look like anything Pokkit related to me. Please confirm that you are running latest version of the plugin and that you have all required dependencies installed.

**Comment by jelebruh** [comment]
> This doesn't look like anything Pokkit related to me. Please confirm that you are running latest version of the plugin and that you have all required dependencies installed.

If i install 21 i see that spigot can't started it. 16.2 latest for 1.13

**Comment by Euro-pol** [comment]
had the same issue a while ago. i needed to make an external database to solve it
