### ISSUE TITLE
[Pokkit] Error loading plugin with Nukkit 1.19

### ISSUE THREAD

**Issue by codekote** [PetteriM1/Pokkit#37]
On server start the errors occured:
```
23:03:11 [ERROR] [Pokkit] Error loading plugin
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at nl.rutgerkok.pokkit.startup.NukkitHook.onLoad(NukkitHook.java:48) [Pokkit-0.11.0.jar:0.11.0]
	at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:269) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:505) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.enchantments.Enchantment.getKey()" because "bukkitWrapper" is null
	at nl.rutgerkok.pokkit.enchantment.PokkitEnchantment.registerNukkitEnchantmentsInBukkit(PokkitEnchantment.java:71) ~[?:?]
	at org.bukkit.craftbukkit.v1_99_R9.CraftServer.<init>(CraftServer.java:134) ~[?:?]
	at nl.rutgerkok.pokkit.Pokkit.onLoad(Pokkit.java:127) ~[?:?]
	... 14 more
...
23:11:00 [ERROR] [Pokkit] Error disabling plugin
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at nl.rutgerkok.pokkit.startup.NukkitHook.onEnable(NukkitHook.java:34) [Pokkit-0.11.0.jar:0.11.0]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:750) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:739) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:582) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Server.getPluginManager()" because the return value of "org.bukkit.Bukkit.getServer()" is null
	at nl.rutgerkok.pokkit.pluginservice.PluginService.enablePlugins(PluginService.java:19) ~[?:?]
	at nl.rutgerkok.pokkit.pluginservice.PluginService.onEnable(PluginService.java:29) ~[?:?]
	at nl.rutgerkok.pokkit.Pokkit.lambda$onEnable$1(Pokkit.java:111) ~[?:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at nl.rutgerkok.pokkit.Pokkit.onEnable(Pokkit.java:111) ~[?:?]
	... 12 more

```

**Comment by PetteriM1** [comment]
Which Nukkit version and Java version are you using?

**Comment by codekote** [comment]
```
23:43:02 [INFO ] This server is running Nukkit version git-e798bac "" (API 1.0.14)

$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```

**Comment by PetteriM1** [comment]
Use Java 8 or 11

**Comment by codekote** [comment]
Both 11 and 8(1.8) had no affect.
Only version  number added to the end of several lines in square bracket
```
21:26:18 [ERROR] [Pokkit] Error loading plugin
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at nl.rutgerkok.pokkit.startup.NukkitHook.onLoad(NukkitHook.java:48) [Pokkit-0.11.0.jar:0.11.0]
	at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:269) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:505) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
	at nl.rutgerkok.pokkit.enchantment.PokkitEnchantment.registerNukkitEnchantmentsInBukkit(PokkitEnchantment.java:71) ~[?:?]
	at org.bukkit.craftbukkit.v1_99_R9.CraftServer.<init>(CraftServer.java:134) ~[?:?]
	at nl.rutgerkok.pokkit.Pokkit.onLoad(Pokkit.java:127) ~[?:?]
	... 14 more

```

**Comment by codekote** [comment]
I fogot to clarify. I use https://github.com/CloudburstMC/Nukkit. But PE 1.18 works fine with your Pokkit

**Comment by PetteriM1** [comment]
Ah it's probably because of that new enchantment added to Nukkit

**Comment by codekote** [comment]
Wow, you fix it! Thanks a lot!
