### ISSUE TITLE
RaspberryJuice fails with Pokkit under Nukkit

### ISSUE THREAD

**Issue by denisglotov** [PetteriM1/Pokkit#7]
RaspberryJuice v.1.11
Pokkit v.0.8.1
Nukkit v.1.0-SNAPSHOT

Looks the plugin does not work with modern version of nukkit. Please advise, if fixing is worth the effort? Or are there good alternatives?

```
$ java -jar nukkit-1.0-SNAPSHOT.jar
...
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchFieldError: GOLD_SWORD
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[?:?]
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.loadPlugin(PokkitPluginLoader.java:113) ~[?:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:272) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.loadPlugins(PokkitPluginManager.java:202) ~[?:?]
        at org.bukkit.craftbukkit.v1_99_R9.CraftServer.loadPlugins(CraftServer.java:706) ~[?:?]
        at nl.rutgerkok.pokkit.pluginservice.PluginService.onLoad(PluginService.java:36) ~[?:?]
        at nl.rutgerkok.pokkit.Pokkit.lambda$onLoad$2(Pokkit.java:121) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at nl.rutgerkok.pokkit.Pokkit.onLoad(Pokkit.java:121) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at nl.rutgerkok.pokkit.startup.NukkitHook.onLoad(NukkitHook.java:40) ~[?:?]
        at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:272) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:481) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NoSuchFieldError: GOLD_SWORD
        at net.zhuoweizhang.raspberryjuice.RaspberryJuicePlugin.<clinit>(RaspberryJuicePlugin.java:19) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[?:?]
        ... 24 more
```

**Comment by PetteriM1** [comment]
Outdated plugin. Pokkit does use 1.13.1 API and `GOLD_SWORD` is called `LEGACY_GOLD_SWORD` in it.

**Comment by denis-papyrus** [comment]
Latest snapshot Nukkit currently only supports API 1.0.9 (matching Minecraft BE clients 1.12 only). What do you mean as '1.13.1' and where could I see the API, please advice.

**Comment by denisglotov** [comment]
Latest snapshot Nukkit currently only supports API 1.0.9 (matching Minecraft BE clients 1.12 only). What do you mean as '1.13.1' and where could I see the API, please advice.

**Comment by PetteriM1** [comment]
> Latest snapshot Nukkit currently only supports API 1.0.9 (matching Minecraft BE clients 1.12 only). What do you mean as '1.13.1' and where could I see the API, please advice.
> 
> UPD: I see that 1.13.1-R0.1-SNAPSHOT is the dependency version of 'spigot-api' that Pocket uses. RaspberryJuice plugin uses 1.12.2-R0.1-SNAPSHOT of 'bukkit'. Do you think that upgrading the plugin to bukkit 1.13.1 helps (since spigot-api includes bukkit, if I got it right)?

Yes. Pokkit does use Bukkit/Spigot 1.13.1-R0.1-SNAPSHOT API. (Maybe going to bump that to 1.13.2) Updating your plugin to use that API will fix this. You can find 1.13 javadocs for example from here: [https://papermc.io/javadocs/paper/1.13/overview-summary.html](url)

**Comment by denisglotov** [comment]
BTW, I prepared a fix here https://github.com/zhuowei/RaspberryJuice/pull/86.
